/**
 * Model Resolver — resolves species to 3D model paths via a 3-tier registry.
 *
 * Lookup order: species → genus → life_form fallback.
 * Registry loaded from public/data/model_registry.json.
 * Available models loaded from public/data/model_manifest.json
 * (auto-generated by scripts/build-model-manifest.js).
 *
 * v2: folder-based structure with variant support.
 * Each entry has { folder, default, variants? } instead of { model }.
 * Path is constructed as folder/default (or folder/variant.file).
 */

let registry = null;

/** Set of GLB paths that exist on disk, loaded from model_manifest.json */
let AVAILABLE_MODELS = new Set();

/** Map of GLB path → thumbnail relative path (e.g. "_thumbnails/eucalyptus_camaldulensis_mature.png") */
let THUMBNAILS = {};

/**
 * Load the model registry and manifest (cached after first call).
 */
async function loadRegistry() {
  if (registry) return registry;

  try {
    const [regResponse, manifestResponse] = await Promise.all([
      fetch('/data/model_registry.json'),
      fetch('/data/model_manifest.json'),
    ]);

    registry = await regResponse.json();

    try {
      const manifest = await manifestResponse.json();
      // Support both old array format and new { models, thumbnails } format
      if (Array.isArray(manifest)) {
        AVAILABLE_MODELS = new Set(manifest);
        THUMBNAILS = {};
      } else {
        AVAILABLE_MODELS = new Set(manifest.models || []);
        THUMBNAILS = manifest.thumbnails || {};
      }
    } catch {
      console.warn('Model manifest not found — no GLB files will be marked as available');
      AVAILABLE_MODELS = new Set();
      THUMBNAILS = {};
    }

    return registry;
  } catch (error) {
    console.error('Error loading model registry:', error);
    return null;
  }
}

/**
 * Build a path from a registry entry's folder and default fields.
 */
function buildPath(entry) {
  if (!entry || !entry.folder || !entry.default) return null;
  return `${entry.folder}/${entry.default}`;
}

/**
 * Select the best variant file for a registry entry.
 * Returns the filename (not full path) to use.
 *
 * @param {object} entry - Registry entry with folder, default, and optional variants
 * @param {object} options - Optional: { variant: string, height: number }
 */
function selectVariant(entry, options = {}) {
  if (!entry?.variants || Object.keys(entry.variants).length === 0) {
    return entry?.default || null;
  }

  // If a specific variant is requested
  if (options.variant && entry.variants[options.variant]) {
    return entry.variants[options.variant].file;
  }

  // If height is provided, find the best matching variant by height_range
  if (options.height != null) {
    for (const [key, variant] of Object.entries(entry.variants)) {
      if (variant.height_range) {
        const [min, max] = variant.height_range;
        if (options.height >= min && options.height <= max) {
          return variant.file;
        }
      }
    }
  }

  // Default
  return entry.default;
}

/**
 * Count total unique registry paths for the availability log.
 */
function countRegistryPaths() {
  if (!registry) return 0;
  const paths = new Set();
  for (const entry of Object.values(registry.species || {})) {
    if (entry?.folder && entry?.default) paths.add(`${entry.folder}/${entry.default}`);
  }
  for (const entry of Object.values(registry.genus || {})) {
    if (entry?.folder && entry?.default) paths.add(`${entry.folder}/${entry.default}`);
  }
  for (const entry of Object.values(registry.life_form || {})) {
    if (entry?.folder && entry?.default) paths.add(`${entry.folder}/${entry.default}`);
  }
  return paths.size;
}

/**
 * Resolve a species to its 3D model path.
 *
 * @param {string} scientificName - Full species name (e.g. "Eucalyptus camaldulensis")
 * @param {string} lifeFormCode   - DSE benchmark LF code (e.g. "IT", "MTG")
 * @param {object} options        - Optional: { variant: string, height: number }
 * @returns {{ path: string, level: string, name: string, available: boolean, thumbnail: string|null } | null}
 */
export function resolveModel(scientificName, lifeFormCode, options = {}) {
  if (!registry) {
    return null;
  }

  // Normalise: strip "var.", "subsp.", and everything after
  const baseName = scientificName
    ? scientificName.replace(/\s+(var\.|subsp\.).*$/, '')
    : null;

  const genus = scientificName ? scientificName.split(' ')[0] : null;

  // 1. Species-level match (try full name first, then base name)
  const speciesEntry = (scientificName && registry.species[scientificName])
    || (baseName && registry.species[baseName])
    || null;

  if (speciesEntry) {
    const file = selectVariant(speciesEntry, options);
    const path = `${speciesEntry.folder}/${file}`;
    return {
      path,
      level: 'species',
      name: baseName || scientificName,
      available: AVAILABLE_MODELS.has(path),
      thumbnail: THUMBNAILS[path] || null,
    };
  }

  // 2. Genus-level match
  if (genus && registry.genus[genus]) {
    const entry = registry.genus[genus];
    const path = buildPath(entry);
    return {
      path,
      level: 'genus',
      name: genus,
      available: AVAILABLE_MODELS.has(path),
      thumbnail: THUMBNAILS[path] || null,
    };
  }

  // 3. Life form fallback
  if (lifeFormCode && registry.life_form[lifeFormCode]) {
    const entry = registry.life_form[lifeFormCode];
    if (entry === null) return null;
    const path = buildPath(entry);
    return {
      path,
      level: 'life_form',
      name: lifeFormCode,
      available: AVAILABLE_MODELS.has(path),
      thumbnail: THUMBNAILS[path] || null,
    };
  }

  return null;
}

/**
 * Initialize the model resolver. Call this early (e.g. on first polygon click).
 * Safe to call multiple times — will only fetch once.
 */
export async function initModelResolver() {
  const reg = await loadRegistry();
  if (reg) {
    const sCount = Object.keys(reg.species).length;
    const gCount = Object.keys(reg.genus).length;
    const lfCount = Object.keys(reg.life_form).filter(k => reg.life_form[k] !== null).length;
    const totalPaths = countRegistryPaths();
    console.log(`Model registry loaded: ${sCount} species, ${gCount} genus, ${lfCount} life form fallbacks`);
    console.log(`Available models: ${AVAILABLE_MODELS.size} of ${totalPaths} registry entries have GLB files`);
  }
  return reg;
}
